FROM python:3.11-slim

WORKDIR /home/fuad/Documents/My_Projects/customer_behavioral
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir fastapi uvicorn pydantic

COPY src/ ./src/

COPY mlruns/ ./mlruns/
COPY mlflow.db .

EXPOSE 8000

CMD ["uvicorn", "src.serving.app:app", "--host", "0.0.0.0", "--port", "8000"]
